# Generated by Django 4.2.5 on 2024-05-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focalpoint', '0002_alter_forum_description'),
        ('users', '0002_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='focalpoint.categorie'),
        ),
    ]
