# Generated by Django 4.2.5 on 2023-10-11 17:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FocalPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('access_code', models.CharField(max_length=55, null=True)),
                ('access_pass', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Point Focal',
                'verbose_name_plural': 'Points Focaux',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='focalpoint/information')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='focalpoint.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationFocalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('focalpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focalpoint.focalpoint')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focalpoint.publication')),
            ],
            options={
                'unique_together': {('publication', 'focalpoint')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='focalpoint',
            field=models.ManyToManyField(through='focalpoint.PublicationFocalPoint', to='focalpoint.focalpoint'),
        ),
        migrations.AddField(
            model_name='publication',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='focalpoint.information'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('media_url', models.CharField(max_length=100, null=True)),
                ('media_type', models.CharField(max_length=100, null=True)),
                ('is_publshed', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='focalpoint.information')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focalpoint.focalpoint')),
            ],
        ),
    ]
