# Generated by Django 4.2.5 on 2023-10-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='media',
        ),
    ]
