# Generated by Django 4.2.5 on 2023-11-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_message_media_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.TextField(null=True),
        ),
    ]
